version: '2'
services:
###########################           服务注册和发现          ####################################

  eureka-server-1:                        # 自定义服务名--注册中心
#    image: flyxiaozhu/eureka-server      # 镜像名称
    build: ./eureka-server/               # 通过Dockerfile自行构建
    image: eureka-server:springcloud
    # always (当容器退出时docker自动重启它)
    # on-failure:10 (当容器非正常退出, 最多自动重启10次, 10之后不再重启)
    restart: always                       # 总是重启
    ports:
      - "7000:7000"
    expose:                               # 暴露端口，只提供容器间访问，不暴露给主机
      - "7000"
    environment:                          # 环境变量
      SPRING_PROFILES_ACTIVE: peer1       # 自定义参数用于给服务的配置文件传递参数

  eureka-server-2:
    build: ./eureka-server/
    image: eureka-server:springcloud
    restart: always
    expose:
      - "7001"
    environment:
      SPRING_PROFILES_ACTIVE: peer2
###########################           spring-boot-admin        ####################################

  admin-server:
    build: ./admin-server/
    image: admin-server:springcloud
    restart: always
    ports:
      - "7020:7020"                                             # 端口映射
    expose:
      - "7020"
    environment:
      SPRING_PROFILES_ACTIVE: secure # 环境选择 搭配 @Profile("insecure") 使用
      SPRING_SECURITY_USER_NAME: flyxiaozhu # 设置登陆的用户名和密码 client为单纯的spring-boot程序
      SPRING_SECURITY_USER_PASSWORD: 123456


###########################           分布式配置中心         ####################################

  config-server-1:
    build: ./config-server/
    image: config-server:springcloud
    restart: always
    expose:
      - "7010"
    environment:
      SPRING_PROFILES_ACTIVE: config1

      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/fiyxiaozhu/SpringCloudConfig
      SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH-PATHS:  respo
      SPRING_CLOUD_CONFIG_LABEL:  master


################################           服务提供者        ########################################

  server-hello-1:
    build: ./server-hello
    image: server-hello-1:springcloud
    restart: always
    ports:
      - "7030:7030"
    expose:
      - "7030"
    environment:
      # 配置中心客户端配置
      SPRING_CLOUD_CONFIG_LABEL: master
      SPRING_CLOUD_CONFIG_PROFILE: dev
      SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED: "true"
      SPRING_CLOUD_CONFIG_DISCOVERY_SERVICE-ID: config-server
      SPRING_CLOUD_CONFIG_FAIL-FAST: "true"
      SPRING_CLOUD_CONFIG_RETRY_INITIAL-INTERVAL: 1000
      SPRING_CLOUD_CONFIG_RETRY_MAX-ATTEMPTS: 6
      SPRING_CLOUD_CONFIG_RETRY_MAX-INTERVAL: 2000
      SPRING_CLOUD_CONFIG_RETRY_MULTIPLIER: 1.1

      # 信息总线配置 rabbitmq配置
      SPRING_RABBITMQ_HOST: 192.168.1.250
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: flyxiaozhu
      SPRING_RABBITMQ_PASSWORD: 1120zh.+
      SPRING_CLOUD_BUS_ENABLED: "true"
      SPRING_CLOUD_BUS_TRACE_ENABLED: "true"                        # 开启信息跟踪

      # zipkin 客户端配置
      SPRING_ZIPKIN_BASE-URL: http://trace-server:7060
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1.0
      SPRING_ZIPKIN_SENDER_TYPE: web



