version: '2'
services:
###########################           服务注册和发现          ####################################

  eureka-server-1:                        # 自定义服务名--注册中心
#    image: flyxiaozhu/eureka-server      # 镜像名称
    build: ./eureka-server/               # 通过Dockerfile自行构建
    image: eureka-server:springcloud
    # always (当容器退出时docker自动重启它)
    # on-failure:10 (当容器非正常退出, 最多自动重启10次, 10之后不再重启)
    restart: always                       # 总是重启
    ports:
      - "7000:7000"
    expose:                               # 暴露端口，只提供容器间访问，不暴露给主机
      - "7000"
    environment:                          # 环境变量
      SPRING_PROFILES_ACTIVE: peer1       # 自定义参数用于给服务的配置文件传递参数


###########################           分布式配置中心         ####################################

  config-server-1:
    build: ./config-server/
    image: config-server:springcloud
    restart: always
    expose:
      - "7010"
    environment:
      SPRING_PROFILES_ACTIVE: config1

      # git 仓库配置
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/fiyxiaozhu/SpringCloudConfig   # 配置git仓库的地址
      SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH-PATHS:  respo                                   # git仓库地址下的相对地址，可以配置多个，用,分割。
#      SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME:                                             # git仓库的用户和密码
#      SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD:
      SPRING_CLOUD_CONFIG_LABEL:  master                                                    # 分支

###########################           spring-boot-admin        ####################################

  admin-server:
    build: ./admin-server/
    image: admin-server:springcloud
    restart: always
    ports:
      - "7020:7020"                                             # 端口映射
    expose:
      - "7020"
    environment:
      SPRING_PROFILES_ACTIVE: secure # 环境选择 搭配 @Profile("insecure") 使用
      SPRING_SECURITY_USER_NAME: flyxiaozhu # 设置登陆的用户名和密码 client为单纯的spring-boot程序
      SPRING_SECURITY_USER_PASSWORD: 123456



