server:
  port: 7003

spring:
  application:
    name: spring-boot-admin-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
#   表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: spring-boot-admin-client:${server.port}
#    表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    lease-expiration-duration-in-seconds: 30
#    表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。默认为30秒
    lease-renewal-interval-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always



