server:
  port: 7001
spring:
  application:
    name: admin-server
  rabbitmq: # rabbitmq配置
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true # 开启消息跟踪


