server:
  port: 7050
spring:
  application:
    name: server-turbine
info:
  version: @project.version@ # 显示版本信息
turbine:
  aggregator:
    cluster-config: default # 指定聚合哪些集群，多个使用","分割，默认为default
  app-config: server-ribbon,server-feign  # 配置Eureka中的serviceId列表，表明监控哪些服务
  clusterNameExpression: new String("default")

#  turbine.clusterNameExpression有几种情形
#  clusterNameExpression指定集群名称，默认表达式appName；此时：turbine.aggregator.clusterConfig需要配置想要监控的应用名称
#  当clusterNameExpression: default时，turbine.aggregator.clusterConfig可以不写，因为默认就是default
#  当clusterNameExpression: metadata['cluster']时，假设想要监控的应用配置了eureka.instance.metadata-map.cluster: ABC，则需要配置，同时turbine.aggregator.clusterConfig: ABC

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-1:7000/eureka/,http://eureka-server-2:7001/eureka/
    healthcheck:
      enabled: true # 开启健康检查（依赖spring-boot-starter-actuator）
  instance:
    lease-expiration-duration-in-seconds: 30 # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-renewal-interval-in-seconds: 10 # 心跳时间，即服务续约间隔时间（缺省为30s）
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"  #暴露所有 endpoints
  endpoint:
    health:
      show-details: always