spring:
  application:
    name: eureka-server
#  profiles:
#    active: peer1
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30 # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-renewal-interval-in-seconds: 10    # 心跳时间，即服务续约间隔时间（缺省为30s）
#  server:
#    enable-self-preservation: false          # 关闭自我保护 默认打开
#    eviction-interval-timer-in-ms: 5000      # 清理服务器  续期时间，即扫描失效服务的间隔时间（缺省为60s）
#  client:
#    healthcheck:
#      enabled: true                          # 开启健康检查（依赖spring-boot-starter-actuator）
management:
  endpoints:
    web:
      base-path: /actuator    # 修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      exposure:
        include: "*"  #暴露所有 endpoints
  endpoint:
    health:
      show-details: always
info:
  version: @project.version@
#      1）springboot项目如果没有指定spring-boot-starter-parent的话，而且想要在配置文件yml或properties上使用@@来获取其它信息等，你就需要在build上增加如下配置：（这个问题就是我公司里的项目上的问题）项目启动或者打包时，IDE会自动将maven信息替换给application配置文件。
#
#  <resources>
#      <resource>
#          <directory>src/main/resources</directory>
#          <filtering>true</filtering>
#      </resource>
#  </resources>
#
#      2）如果你的项目有继承spring-boot-starter-parent的话，就不用加上面的配置信息。
