server:
  port: 7000
spring:
  profiles: peer1
eureka:
  client:
#    register-with-eureka: false # 不向注册中心注册自己
#    fetch-registry: false # 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:  # docker 下 defaultZone发现服务的host改为镜像名。
      defaultZone: http://flyxiaozhu:123456@eureka-server-2:7001/eureka/ # 地址
