server:
  port: 7002
spring:
  application:
    name: config-server
#   git 仓库配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fiyxiaozhu/SpringCloudConfig # 配置git仓库的地址
          search-paths: respo  # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:  # git仓库的用户和密码
          password:
      label: master # 分支
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/